### ISSUE TITLE
Figure out a way to index Pads across a network

### ISSUE THREAD

**Issue by boonebgorges** [boonebgorges/participad#10]
If Pads are stored as CPT data on individual sites, there should be some system in place to allow looking up Pads across a network - at least, as indexed by user.

Could be tied to BP?

**Comment by JohnMcLear** [comment]
@boonebgorges By Network do you mean a network of WP sites IE WP multisite?  Could you be a bit more specific what needs to change here as it's a bit confusing.

Cheers

**Comment by boonebgorges** [comment]
Yes, I mean a WP multisite network.

The idea when I opened this ticket was that you would have pad content
being saved on individual sites in the network, but it would be nice to
have a network-wide listing of pads as well. In retrospect, this might
not be necessary (at least it's not for my current client). So I'm going
to close this for the time being.
