### ISSUE TITLE
Acivating Participad - fatal error

### ISSUE THREAD

**Issue by opn** [boonebgorges/participad#25]
Fatal error: Uncaught exception 'InvalidArgumentException' with message '[/] is not a valid URL' in /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/participad/lib/etherpad-lite-client.php:21 Stack trace: #0 /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/participad/includes/class-participad-client.php(30): EtherpadLiteClient->__construct(false, '/') #1 /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/participad/includes/functions.php(13): Participad_Client::instance() #2 /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/participad/includes/functions.php(71): participad_client() #3 /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/participad/includes/class-participad-integration.php(93): participad_is_installed_correctly() #4 /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/participad/modules/dashboard/dashboard.php(23): Participad_Integration->init() #5 /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/par in /home/liquidadmin1/blog.parliamentofthings.org/wp-content/plugins/participad/lib/etherpad-lite-client.php on line 21

**Comment by opn** [comment]
Hi not sure where to ask for help. Apologies if this is not the right forum. I'm keen to get Participad up and start using the http api.

Installing the Wordpress hosted version crashes the entire site immediately. I have to remove the Participad plugin folder manually using FTP.

Are you saying that This issue has been fixed and that installing the latest version via git would fix this for me? Or is there something else I should do.

Thanks

**Comment by AramZS** [comment]
Yup, looks like overwriting my Participad from the plugins directory with the version from this git's master branch has fixed the error.

**Comment by JohnMcLear** [comment]
Awesome thanks @boonebgorges

**Comment by boonebgorges** [comment]
@opn Yes, the latest update fixes it.

@AramZS Thanks!

@JohnMcLear You're welcome :)
