### ISSUE TITLE
Feature request: easy method of associating Notepad to Post in Dashboard

### ISSUE THREAD

**Issue by amandafrench** [boonebgorges/participad#26]
Since a user can create a Notepad through the Dashboard, it'd be nice if that Notepad could be associated with a post after its creation in some more evident way than by using the Custom Field "notepad-associated-post" and putting in the post ID.

**Comment by boonebgorges** [comment]
Maybe better: don't allow users to create Notepads through the
Dashboard? What do you think?

**Comment by amandafrench** [comment]
I actually think that's a great idea. It's a bit confusing.

**Comment by amandafrench** [comment]
I do worry that people won't realize they need to use the Create Notepad and Notepad Info widgets, though, and if they don't they won't be able to access the notepads. Maybe rename those Create Participad and Participad Info?

**Comment by boonebgorges** [comment]
Good idea. We have a convention in BuddyPress and bbPress of appending
the plugin name to widget titles in the Dashboard, like this:

(Participad) Create Notepad
(Participad) Notepad Info

I think this'd be a good way forward.

**Comment by amandafrench** [comment]
I approve.

**Comment by amandafrench** [comment]
Although technically that's "prepending."

**Comment by boonebgorges** [comment]
It was definitely worth leaving the extra comment to correct me :-D

**Comment by amandafrench** [comment]
Excellent use of "prepend" in a sentence / commit.

**Comment by JohnMcLear** [comment]
Thanks @boonebgorges
