### ISSUE TITLE
Media handling

### ISSUE THREAD

**Issue by amandafrench** [boonebgorges/participad#27]
The WordPress "Add Media" button is still active when Participad is activated, but one can't add images or other media to the text-only pad. Further, when there's a post with an embedded image and Participad is then activated, editing that post from the frontend in Etherpad mode deletes the image.

**Comment by amandafrench** [comment]
Despite what I said in #26, I almost wonder if better functionality for THATCamp would be to _just_ have collaboratively editable "Notepads" and not replace the WP post editing interface with Etherpad. That might not be broadly useful for others, but then again it might. Keep the "Notepad" menu in the Dashboard but build a way there to associate a Notepad with posts, and keep the widgets and the front-end editing of Notepads, but not allow collaborative editing of posts on the frontend. Don't know whether that's technically feasible, but I've already gotten comments from site admins who don't like having the native WP post editor replaced.

**Comment by boonebgorges** [comment]
There are checkboxes in Dashboard > Settings > Participad to turn off
the Editor replacement.

**Comment by amandafrench** [comment]
THE DEUCE YOU SAY

**Comment by amandafrench** [comment]
never mind

**Comment by boonebgorges** [comment]
I thought of everything! Though, on a site like thatcamp.org, it might
be nice if it were possible to configure the default settings (so that
newly created sites would have certain bits turned off, etc).

**Comment by amandafrench** [comment]
Don't try to sugarcoat it. My bad. But yes: if Participad holds up, I'd rather like to Network Activate it on all sites with the Dashboard and possibly also the Frontend setting disabled and the Notepad setting enabled by default.

**Comment by boonebgorges** [comment]
Actually, in your case, because new sites are cloned from your default
site, the settings will carry over too. It's just existing sites that
would be affected. But I'll think about ways to work through this.
