### ISSUE TITLE
Feature request: save a couple revisions

### ISSUE THREAD

**Issue by amandafrench** [boonebgorges/participad#33]
One recent Notepad apparently got written over / blanked out, so I went to see if I could roll it back to an earlier revision, but no dice -- not through the Notepad screen and not directly in the database. It'd be great to have a revision history available, even one that only saves every 10 minutes or so.

**Comment by amandafrench** [comment]
Although if it saved every 10 minutes from now till like the year 3000 or the end of days, whichever comes first, that'd be bad.

**Comment by boonebgorges** [comment]
It's odd that you weren't able to view history on the Etherpad end. The
slider just didn't roll back?

**Comment by amandafrench** [comment]
Ooh, I didn't try looking at it on the Etherpad end, mainly because I, um, don't know where that is or how to do it.

**Comment by amandafrench** [comment]
WHOA, I figured it out. Sweet. Cool. All is good. Never mind.

**Comment by boonebgorges** [comment]
Nice. I seem to recall originally not building in revision support
because of how awesome Etherpad's was.

**Comment by JohnMcLear** [comment]
<3 -- For future reference you might want to supply a UI for rolling back to some older contents or for "forking" a previous state.  We provide an API for this.
